<?php 
	session_start(); 
	include('header.php');
	if (!isset($_SESSION['email'])) 
	{
		$_SESSION['msg'] = "You must log in first";
		header('location: index.php');
	}

	if (isset($_GET['logout'])) 
	{
		session_destroy();
		unset($_SESSION['email']);
		header("location: index.php");
	}

?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Section 13 - Customer Identification</title>
  
 
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="assets/css/sections/section1.0.css">
</head>
<body >
  <main class="">
  <div class="container" style=" width: auto;padding-top: 30px; padding-bottom:30px;">
      <div class="form">
        <div class=" no-gutters" style=" width: auto;">
        <div class="col-md-12" style=" width: auto;" >
            <div class="card-body" style="border-radius: 5%; background-color: #e0dbd3; width: auto;  ">
            <div class="" syle="width: auto;">
                        <h1 class=" text-center login-title text-dark" style="font-size: 40px;">Section 13 - Customer Identification<h1>
                        <p class=" text-center p-1 m-0 font-ubuntu text-black-50">This section will help us to understand the solidity of your sales performance, who your ideal customer is, and how you reach them.</p>
                      </div>
                      <div style="padding: 75px 20% 75px 20%;">
                
                  <form action="store13.php" method="post" class="form-section">

				  	<div class="">
                    	<label>What percentage of your total sales is generated by your top 5 customers?</label>
                    </div>
                    <div align="left" >
                    	<input type = "radio" name = "13-1"class="" value="3" required>Greater than 75%
						<br><input  type = "radio" name = "13-1" class="" value="2" required>Between 40% and 75%
            <br><input  type = "radio" name = "13-1" class="" value="1" required>Less than 40%
            <br><input  type = "radio" name = "13-1" class="" value="0" required>Less than 25%
						
					</div>
<br>
					<div class="">
                    	<label>How would you describe your target customer list?</label>
                    </div>
                    <div align="left" >
                    	<input type = "radio" name = "13-2"class="" value="0" required>What list?
						<br><input  type = "radio" name = "13-2" class="" value="2" required>Small list of focused potential customers
						<br><input  type = "radio" name = "13-2" class="" value="3" required>Solid list of several potential customers
            <br><input  type = "radio" name = "13-2" class="" value="4" required>Long list of many potential customers
            <br><input  type = "radio" name = "13-2" class="" value="5" required>Our customers come to us
            <br><input  type = "radio" name = "13-2" class="" value="1" required>Other

					</div>
<br>
					<div class="">
                    	<label>How would you describe your target market?</label>
                    </div>
                    <div align="left" >
                    	<input type = "radio" name = "13-3"class="" value="2" required>Relatively limited but highly targeted market
						<br><input  type = "radio" name = "13-3" class="" value="3" required>Solid market potential
            <br><input  type = "radio" name = "13-3" class="" value="4" required>Massive market potential
            <br><input  type = "radio" name = "13-3" class="" value="1" required>Other
						
					</div>
<br>
					<div class="">
                    	<label>Do you have a clear profile of your ideal customer?</label>
                    </div>
                    <div align="left" >
                    	<input type = "radio" name = "13-4"class="" value="2" required>Yes
						<br><input  type = "radio" name = "13-4" class="" value="1" required>No
						<br><input  type = "radio" name = "13-4" class="" value="0" required>Don't know
						
            </div>
<br>
					<div class="">
                    	<label>Are your customers readily accessible geographically?</label>
                    </div>
                    <div align="left" >
                    	<input type = "radio" name = "13-5"class="" value="2" required>Yes
						<br><input  type = "radio" name = "13-5" class="" value="1" required>No
						
					</div>
<br>
          <div class="">
                    	<label>Are your customers readily accessible digitally?</label>
                    </div>
                    <div align="left" >
                    	<input type = "radio" name = "13-6"class="" value="2" required>Yes
						<br><input  type = "radio" name = "13-6" class="" value="1" required>No

					</div>
<br>
          <div class="">
                    	<label>Do you have previous experience successfully selling other products/services to this customer set?</label>
                    </div>
                    <div align="left" >
                    	<input type = "radio" name = "13-7"class="" value="2" required>Yes
						<br><input  type = "radio" name = "13-7" class="" value="1" required>No
						
					</div>
<br>
          <div class="">
                    	<label>How would you rate the customer relations overall?</label>
                    </div>
                    <div align="left" >
                    	<input type = "radio" name = "13-8"class="" value="0" required>Poor
						<br><input  type = "radio" name = "13-8" class="" value="1" required>Worse than Average
						<br><input  type = "radio" name = "13-8" class="" value="2" required>Average
            <br><input  type = "radio" name = "13-8" class="" value="3" required>Better than Average
            <br><input  type = "radio" name = "13-8" class="" value="4" required>Excellent

					</div>
<br>
          <div class="">
                    	<label>Do you get referral business from existing customers?</label>
                    </div>
                    <div align="left" >
                    	<input type = "radio" name = "13-9"class="" value="1" required>Yes
						<br><input  type = "radio" name = "13-9" class="" value="0" required>No

					</div>

                      

                      <br>
                    <a href="section14pre.php"><button type="submit" name = "next1" class="btn btn-primary">Next</button></a>
                
                  </form> 
      
                  
                
               
                
                
              </div>
              <div style="text-align: center;">
              <p><em>Section 13 = DONE! Did you know that understanding your ideal customer can massively compound your success? Amazon, Apple, and Costco commit tremendous resources to understanding customers.</em></p>
              <p><span style="color: #ff6600;"><em><strong>End of Section 13 - Customer Identification</strong></em></span></p>
              </div>
            </div>
         
          </div>
        </div>
      </div>
    </div>
  </main>
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>
</html>
